import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { collectMermaidFences, diagramId, extractFenceBody, matchMermaidFenceOpen, parseAlt } from '../scripts/lib/mermaid-fences.mjs';
import { renderDiagrams } from '../scripts/render-diagrams.mjs';
import { createDocsFixture, runEntryPoint } from './cli-fixture.ts';

const renameControl = vi.hoisted(() => ({ failAt: 0, calls: 0, rmFailure: '', rmFailures: 0, readFailure: '' }));
vi.mock('node:fs/promises', async (importOriginal) => { const fs = await importOriginal<typeof import('node:fs/promises')>(); return { ...fs, rename: async (...args: Parameters<typeof fs.rename>) => { renameControl.calls++; if (renameControl.calls === renameControl.failAt) throw new Error('injected rename failure'); return fs.rename(...args); }, rm: async (...args: Parameters<typeof fs.rm>) => { if (renameControl.rmFailure && args[0] === renameControl.rmFailure) { renameControl.rmFailures++; throw new Error('injected rollback removal failure'); } return fs.rm(...args); }, readFile: async (...args: Parameters<typeof fs.readFile>) => { if (renameControl.readFailure && args[0] === renameControl.readFailure) throw Object.assign(new Error('injected skill read failure'), { code: 'EACCES' }); return fs.readFile(...args); } }; });

const script = new URL('../scripts/render-diagrams.mjs', import.meta.url);
const docs = 'website/src/content/docs';
const spec = 'docs/spec';
const skill = '.agents/skills/docs-writing/references/blocks.mdx';
const fixtures: ReturnType<typeof createDocsFixture>[] = [];
afterEach(() => { renameControl.failAt = 0; renameControl.calls = 0; renameControl.rmFailure = ''; renameControl.rmFailures = 0; renameControl.readFailure = ''; fixtures.splice(0).forEach((f) => f.dispose()); });
const fence = (body: string, open = '```mermaid alt="diagram"', close = '```') => `${open}\n${body}\n${close}\n`;
const body = 'flowchart LR\n  A --> B';
const fake = vi.fn(async (id: string, source: string) => ({ light: `<svg data-id="${id}">${source}</svg>`, dark: `<svg data-theme="dark">${source}</svg>` }));
function fixture(files: Record<string, string> = {}) { const f = createDocsFixture(files); mkdirSync(f.website, { recursive: true }); fixtures.push(f); return f; }
function paths(f: ReturnType<typeof fixture>) { return { roots: { docsRoot: join(f.root, docs), specRoot: join(f.root, spec), skillRoot: join(f.root, skill) }, outDir: join(f.website, 'public/diagrams') }; }
function asset(f: ReturnType<typeof fixture>, id: string, theme: 'light' | 'dark') { return join(paths(f).outDir, `${id}.${theme}.svg`); }
function files(f: ReturnType<typeof fixture>) { const out = paths(f).outDir; return existsSync(out) ? readdirSync(out) : []; }

describe('TEST-15 shared Mermaid fence contract', () => {
  it('hashes the normalized body with the first 12 SHA-256 hex characters', () => { expect(diagramId(body)).toBe(createHash('sha256').update(body).digest('hex').slice(0, 12)); expect(diagramId(`${body}\n`)).not.toBe(diagramId(body)); });
  for (const [meta, expected] of [['alt="Diagram"', 'Diagram'], ['alt="a b"', 'a b'], ['', null], ['alt=""', null], ["alt='x'", null], ['alt="x" extra', null], ['other alt="x"', null], ['alt="x\ny"', null]] as const) it(`parses alt metadata ${JSON.stringify(meta)}`, () => { expect(parseAlt(meta)).toBe(expected); });
  it('removes up to opening indentation from each line and joins with LF', () => { expect(extractFenceBody(['  A', ' B', '', '   C'], 2)).toBe('A\nB\n\n C'); });
  for (const [line, expected] of [['```mermaid', { indent: 0, fence: '```', info: 'mermaid' }], [' ````mermaid alt="x"', { indent: 1, fence: '````', info: 'mermaid alt="x"' }], ['~~~mermaid alt="x"', { indent: 0, fence: '~~~', info: 'mermaid alt="x"' }], ['```mermaidx', null], ['```Mermaid', null], ['> ```mermaid', null]] as const) it(`recognizes opener ${line}`, () => { expect(matchMermaidFenceOpen(line)).toEqual(expected); });
  it('allows backticks in a tilde fence info string but rejects them in a backtick fence', () => { expect(matchMermaidFenceOpen('~~~mermaid alt="Use `code`"')).toEqual({ indent: 0, fence: '~~~', info: 'mermaid alt="Use `code`"' }); expect(matchMermaidFenceOpen('```mermaid alt="Use `code`"')).toBeNull(); });
  it('scans only the three documented roots and excludes the synchronized spec copy', async () => { const f = fixture({ [`${spec}/a.md`]: fence('A'), [`${docs}/en/a.mdx`]: fence('B'), [`${docs}/spec/a.md`]: fence('ignored'), [skill]: fence('C'), 'README.md': fence('outside') }); const found = await collectMermaidFences(paths(f).roots); expect(found.map((x) => x.body).sort()).toEqual(['A', 'B', 'C']); expect(found).toEqual(expect.arrayContaining([expect.objectContaining({ file: join(f.root, `${spec}/a.md`), line: 1, id: diagramId('A'), body: 'A', alt: 'diagram' })])); });
  it('ignores an absent optional skill file', async () => { const f = fixture({ [`${spec}/a.md`]: fence('A') }); expect((await collectMermaidFences(paths(f).roots)).map((x) => x.body)).toEqual(['A']); });
  it('collects authored MDX fences inside the docs spec directory', async () => { const f = fixture({ [`${docs}/spec/example.mdx`]: fence('authored') }); expect(await collectMermaidFences(paths(f).roots)).toContainEqual(expect.objectContaining({ file: join(f.root, `${docs}/spec/example.mdx`), body: 'authored', alt: 'diagram' })); });
  it('propagates a non-ENOENT skill file read failure', async () => { const f = fixture({ [skill]: fence('A') }); renameControl.readFailure = paths(f).roots.skillRoot; await expect(collectMermaidFences(paths(f).roots)).rejects.toMatchObject({ code: 'EACCES', message: 'injected skill read failure' }); });
  it('recognizes backtick and tilde fences but not a language prefix', async () => { const f = fixture({ [`${spec}/a.md`]: [fence('A'), fence('B', '````mermaid alt="b"', '````'), fence('C', '~~~mermaid alt="x"', '~~~'), fence('ignored', '```mermaidx')].join('\n') }); expect((await collectMermaidFences(paths(f).roots)).map(({ body, alt }) => [body, alt])).toEqual([['A', 'diagram'], ['B', 'b'], ['C', 'x']]); });
  it('keeps the documented scanner limitations for blockquotes and HTML comments', async () => { const f = fixture({ [`${spec}/a.md`]: `> ${fence('quoted').replaceAll('\n', '\n> ')}\n<!--\n${fence('commented')}-->\n` }); expect((await collectMermaidFences(paths(f).roots)).map((x) => x.body)).toEqual(['commented']); });
  it('gives indented and flush fences the same body and id', async () => { const f = fixture({ [`${spec}/a.md`]: ` ${fence(' A\n B', ' ```mermaid alt="x"', ' ```')}${fence('A\nB')}` }); const found = await collectMermaidFences(paths(f).roots); expect(found.map((x) => [x.body, x.id])).toEqual([["A\nB", diagramId('A\nB')], ["A\nB", diagramId('A\nB')]]); });
  it('normalizes CRLF once and recognizes the same fence as LF', async () => { const f = fixture({ [`${spec}/lf.md`]: fence(body), [`${spec}/crlf.md`]: fence(body).replaceAll('\n', '\r\n') }); const found = await collectMermaidFences(paths(f).roots); expect(found.map((x) => [x.id, x.body])).toEqual([[diagramId(body), body], [diagramId(body), body]]); });
});

describe('TEST-15 SVG batch publication', () => {
  it('writes both variants from one renderer result', async () => { const f = fixture({ [`${spec}/a.md`]: fence(body) }); const renderer = fake.mockClear(); await renderDiagrams({ ...paths(f), renderer }); expect(renderer).toHaveBeenCalledExactlyOnceWith(diagramId(body), body); expect(readFileSync(asset(f, diagramId(body), 'light'), 'utf8')).toBe(`<svg data-id="${diagramId(body)}">${body}</svg>`); expect(readFileSync(asset(f, diagramId(body), 'dark'), 'utf8')).toBe(`<svg data-theme="dark">${body}</svg>`); });
  it('skips an existing complete pair, including on a second run', async () => { const f = fixture({ [`${spec}/a.md`]: fence(body) }); const { outDir } = paths(f); mkdirSync(outDir, { recursive: true }); for (const theme of ['light', 'dark'] as const) writeFileSync(asset(f, diagramId(body), theme), theme); const renderer = fake.mockClear(); await renderDiagrams({ ...paths(f), renderer }); expect(renderer).not.toHaveBeenCalled(); await renderDiagrams({ ...paths(f), renderer }); expect(renderer).not.toHaveBeenCalled(); for (const theme of ['light', 'dark'] as const) expect(readFileSync(asset(f, diagramId(body), theme), 'utf8')).toBe(theme); });
  it('renders one id once for the same body with different alt text', async () => { const f = fixture({ [`${spec}/a.md`]: fence(body, '```mermaid alt="first"'), [`${docs}/en/b.mdx`]: fence(body, '~~~mermaid alt="second"', '~~~') }); const renderer = fake.mockClear(); await renderDiagrams({ ...paths(f), renderer }); expect(renderer).toHaveBeenCalledTimes(1); });
  it('rejects missing or malformed alt before publishing', async () => { const f = fixture({ [`${spec}/a.md`]: fence(body, '```mermaid') }); const renderer = fake.mockClear(); await expect(renderDiagrams({ ...paths(f), renderer })).rejects.toThrow(/alt/i); expect(renderer).not.toHaveBeenCalled(); expect(files(f).filter((x) => x.endsWith('.svg'))).toEqual([]); });
  it('retains existing assets and leaves no temporary files after a render failure', async () => { const f = fixture({ [`${spec}/a.md`]: fence('good') + fence('bad') }); const old = diagramId('old'); const { outDir } = paths(f); mkdirSync(outDir, { recursive: true }); writeFileSync(asset(f, old, 'light'), 'old-light'); writeFileSync(asset(f, old, 'dark'), 'old-dark'); const renderer = vi.fn(async (_id: string, source: string) => { if (source === 'bad') throw new Error('syntax error'); return { light: 'new-light', dark: 'new-dark' }; }); await expect(renderDiagrams({ ...paths(f), renderer })).rejects.toThrow('syntax error'); expect(files(f).filter((x) => x.endsWith('.svg'))).toEqual([`${old}.dark.svg`, `${old}.light.svg`]); expect(files(f).filter((x) => x.includes('.tmp-'))).toEqual([]); expect(readFileSync(asset(f, old, 'light'), 'utf8')).toBe('old-light'); });
  it('rolls back the first placement and removes later temps when the second rename fails', async () => { const f = fixture({ [`${spec}/a.md`]: fence('A') + fence('B') }); const old = diagramId('old'); mkdirSync(paths(f).outDir, { recursive: true }); writeFileSync(asset(f, old, 'light'), 'old-light'); writeFileSync(asset(f, old, 'dark'), 'old-dark'); renameControl.calls = 0; renameControl.failAt = 2; await expect(renderDiagrams({ ...paths(f), renderer: fake.mockClear() })).rejects.toThrow('injected rename failure'); expect(files(f)).toEqual([`${old}.dark.svg`, `${old}.light.svg`]); expect(readFileSync(asset(f, old, 'light'), 'utf8')).toBe('old-light'); });
  it('reports a rollback removal failure while preserving the publication error', async () => { const f = fixture({ [`${spec}/a.md`]: fence('A') }); renameControl.calls = 0; renameControl.failAt = 2; renameControl.rmFailure = asset(f, diagramId('A'), 'light'); const stderr = vi.spyOn(console, 'error').mockImplementation(() => {}); try { await expect(renderDiagrams({ ...paths(f), renderer: fake.mockClear() })).rejects.toThrow('injected rename failure'); expect(renameControl.rmFailures).toBe(1); expect(stderr).toHaveBeenCalledWith(expect.stringMatching(/rollback|remove/i), expect.objectContaining({ message: 'injected rollback removal failure' })); } finally { stderr.mockRestore(); } });
  it('deletes orphan SVGs only after all rendering succeeds', async () => { const f = fixture({ [`${spec}/a.md`]: fence(body) }); const old = diagramId('old'); mkdirSync(paths(f).outDir, { recursive: true }); writeFileSync(asset(f, old, 'light'), 'old'); await renderDiagrams({ ...paths(f), renderer: fake.mockClear() }); expect(existsSync(asset(f, old, 'light'))).toBe(false); });
  it('preserves orphan SVGs when a renderer fails', async () => { const f = fixture({ [`${spec}/a.md`]: fence(body) }); const old = diagramId('old'); mkdirSync(paths(f).outDir, { recursive: true }); writeFileSync(asset(f, old, 'light'), 'old'); await expect(renderDiagrams({ ...paths(f), renderer: vi.fn().mockRejectedValue(new Error('syntax error')) })).rejects.toThrow(); expect(readFileSync(asset(f, old, 'light'), 'utf8')).toBe('old'); });
  it('uses the real CLI failure status for a syntax error', () => { const f = fixture({ [`${spec}/a.md`]: fence('flowchart LR\n  A -->') }); const result = runEntryPoint(script, f.website); expect(result.status).toBe(1); expect(result.stderr).toMatch(/(error|syntax|mermaid)/i); });
});
